backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "produk"
    label: "Produk"
    folder: "produk"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nama Produk", name: "title", widget: "string" }
      - { label: "Harga", name: "harga", widget: "string" }
      - { label: "Deskripsi", name: "body", widget: "markdown" }
      - { label: "Link Shopee", name: "link", widget: "string" }
      - { label: "Gambar", name: "image", widget: "image" }
